from .room import Room

class Labyrinth:
    def __init__(self):
        self.room_list = []
        start = Room()
        room1 = Room()
        start.add_route(room1.id, Room.Direction.WEST)
        room2 = Room()
        start.add_route(room2.id, Room.Direction.EAST)
        room3 = Room()
        start.add_route(room3.id, Room.Direction.NORTH)
        self.room_list.append(start)
        room1.add_route(start.id, Room.Direction.EAST)
        self.room_list.append(room1)
        room2.add_route(start.id, Room.Direction.WEST)
        room4= Room()
        room4.add_type(Room.Type.PORTAL)
        room2.add_route(room4.id, Room.Direction.NORTH)
        self.room_list.append(room2)
        room4.add_route(room2.id, Room.Direction.SOUTH)
        room4.add_route(room3.id, Room.Direction.WEST)
        self.room_list.append(room4)
        room5 = Room()
        room3.add_route(start.id, Room.Direction.SOUTH)
        room3.add_route(room4.id, Room.Direction.EAST)
        room3.add_route(room5.id, Room.Direction.NORTH)
        self.room_list.append(room3)
        room6 = Room()
        room7 = Room()
        room8 = Room()
        room5.add_route(room3.id, Room.Direction.SOUTH)
        room5.add_route(room6.id, Room.Direction.WEST)
        room5.add_route(room7.id, Room.Direction.EAST)
        room5.add_route(room8.id, Room.Direction.NORTH)
        self.room_list.append(room5)
        room9 = Room()
        room9.add_type(Room.Type.WITH_KEY)
        room6.add_route(room5.id, Room.Direction.EAST)
        room6.add_route(room9.id, Room.Direction.NORTH)
        self.room_list.append(room6)
        room9.add_route(room6.id, Room.Direction.SOUTH)
        self.room_list.append(room9)
        room10 = Room()
        room10.add_type(Room.Type.PORTAL)
        room11 = Room()
        room12 = Room()
        room10.add_route(room11.id, Room.Direction.EAST)
        room10.add_route(room12.id, Room.Direction.NORTH)
        self.room_list.append(room10)
        room11.add_route(room10.id, Room.Direction.WEST)
        self.room_list.append(room11)
        room12.add_route(room10.id, Room.Direction.SOUTH)
        self.room_list.append(room12)
        room13 = Room()
        room7.add_route(room5.id, Room.Direction.WEST)
        room7.add_route(room13.id, Room.Direction.NORTH)
        self.room_list.append(room7)
        room8.add_route(room5.id, Room.Direction.SOUTH)
        room8.add_route(room13.id, Room.Direction.EAST)
        self.room_list.append(room8)
        room14 = Room()
        room14.add_type(Room.Type.EXIT)
        room13.add_route(room7.id, Room.Direction.SOUTH)
        room13.add_route(room8.id, Room.Direction.WEST)
        room13.add_route(room14.id, Room.Direction.EAST)
        self.room_list.append(room13)
        room14.add_route(room13.id, Room.Direction.WEST)
        self.room_list.append(room14)


       
        